sudo: required

language: java

jdk:
  - oraclejdk8

services:
  - docker
install:
#  - cd src/main/gui/ && npm install && bower install
#  - grunt build --force
#  - cd ../../../
  - mvn install -Dmaven.javadoc.skip=true -B -V
#  - mvn -DskipTests=true install -Dmaven.test.skip=true -Dmaven.javadoc.skip=true -B -V

before_install:
#  - sudo apt-get update && sudo apt-get install -y nodejs npm
#  - npm install -g grunt grunt-cli bower
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

after_success:
  - docker build -t fgiana/yoalert:latest .
  - docker run --name yoalert -d -P fgiana/yoalert:latest
  - docker ps
  - docker port yoalert
  - docker push fgiana/yoalert:latest

