version: '2'
services:
  alertas:
    build: .
    #image: "fgiana/yoalert"
    ports:
     - "8080:8080"
     - "8181:8080"
    links:
      - db:database
    environment:
     - DB_PASSWORD=yomeanim
     - DB_USERNAME=alertas
     - DB_HOST=database
     - DB_NAME=alertas
     - SENDINBLUE_KEY=GjrYSxIvUkc98sDq
     - EMAIL_TO=gianafrancisco@gmail.com,seguros@yomeanimoyvos.com
     - LEADS_TOKEN=EAADLHFkfsMgBAGFRCp3eodVMMHvsZA72p7Y0FZBz2xJqnmUf4sffP1CMhazhI6xNHzmA9KILnEhmfumk9iicQRqV2OZBj9zWvqF0Ixvju17HQQ5DnZBZCpUoOfiF3mSMQbPD4ZCZCru7fczZBSrljRJY20ot5APaqXoZD
    volumes:
     - /hosthome/fransis/git/mevoyseguro/site/mevoyseguro.com/:/var/www/html/
  db:
    image: "mariadb:10.0.31"
    volumes:
     - /database/:/var/lib/mysql/
     #- sql/:/docker-entrypoint-initdb.d/
     - /hosthome/fransis/git/yoAlert/sql/:/docker-entrypoint-initdb.d/
    environment:
     - MYSQL_USER=alertas
     - MYSQL_PASSWORD=yomeanim
     - MYSQL_DATABASE=alertas
     - MYSQL_ROOT_PASSWORD=yomeanim
    ports:
     - "3306:3306"
